bufak-wiwi/administration-panel

src/App.js
src/components/Layout/Sidebar.js
src/components/MissinPermissions.js
src/components/PrivateRoute.js
src/pages/ApplicationPage.js
src/pages/DashboardPage.js
src/pages/administrator/PhasesPage.js
src/redux/conferenceRedux.js
src/redux/councilRedux.js
src/sagas/authSagas.js
src/sagas/conferenceSagas.js
src/sagas/councilSagas.js
src/sagas/index.js
src/utils/functions.js

Contains:
- Administrator routes
- SuperAdmin routes
- settings page for phases
- fixed warnings

Administrator Settings for phases

---

src/App.js
src/components/Layout/Sidebar.js
src/components/PrivateRoute.js
src/components/SearchInput.js
src/pages/administrator/ApplicationDetailsPage.js
src/pages/administrator/ApplicationListPage.js
src/redux/conferenceRedux.js
src/sagas/conferenceSagas.js
src/sagas/index.js
src/utils/functions.js

Enables Administrators to:
- View all applications
- Change status of multiple applications based on current filter & search
- Change single application inside applicationDetails

Manage applications

---

src/App.js
src/components/PrivateRoute.js

feat(): login redirects to the correct route

---

src/components/AuthForm.js
src/redux/authRedux.js
src/sagas/authSagas.js
src/sagas/index.js

fixes #15 
password forgot option will sen firebase reset email.

feat(authPage): password forgot option

---

src/components/AuthForm.js
src/sagas/authSagas.js

new created user gets logged in automatically

feat(authForm): created user get logged in

---

src/App.js
src/components/Layout/Sidebar.js
src/pages/ProfilePage.js
src/redux/authRedux.js
src/redux/conferenceRedux.js
src/sagas/authSagas.js
src/sagas/index.js

Profile Page is shown into sidebar. Updating the profile is only allowed, if data is valid (here not empty).
fixes #20

Profile page

---

src/pages/administrator/ApplicationListPage.js

fix(applicationlist): switched surname and name

---

src/App.js
src/components/AuthForm.js
src/components/Layout/Footer.js
src/pages/DataProtectionPage.js

DataProtectionStatement

---

src/pages/administrator/ApplicationDetailsPage.js

fix(): correct description for priority

---

src/pages/administrator/ApplicationDetailsPage.js

fix(applicationDetails): username in correct order

---

src/utils/functions.js

- User will be logged out, when receiving a 401 or 418 http status code
- fixes #23

feat(): force logout when receiving 401 or 418

---

package.json
src/App.js
src/components/Delay.js
src/components/Delete.js
src/components/DetailsBody.js
src/components/DetailsHeader.js
src/components/Layout/Sidebar.js
src/pages/administrator/PhasesPage.js
src/pages/administrator/WorkshopDetailsPage.js
src/pages/administrator/WorkshopListPage.js
src/redux/index.js
src/redux/workshopRedux.js
src/sagas/conferenceSagas.js
src/sagas/index.js
src/sagas/workshopSagas.js
yarn.lock

fixes #34 
fixes #35 
fixes #36

35 workshops

---

package.json
src/components/DetailsBody.js
src/pages/ProfilePage.js
src/pages/administrator/ApplicationDetailsPage.js
src/pages/administrator/WorkshopDetailsPage.js
src/redux/authRedux.js
src/sagas/conferenceSagas.js
src/utils/functions.js
yarn.lock

ApplicaitonDetailsPage and profilePage now using:
```
<DetailsHeader
title={ application.user.name + ' ' + application.user.surname}
empty={false}
editing={editing}
onEdit={() => this.setState({ editing: true})}
onCancel={() => this.onCancel()}
onSave={() => this.onSave()}
disabled={false}
/>
<DetailsBody
disabled={!editing}
object={this.state.application}
onChange={(id, value) => this.setState({ application: {...application, [id]: value}})}
properties={properties}
/>  
```
In addition, all pages use the new function `shouldObjectBeUpdated` so that a consistent behavior is granted.

Refactor detailsPages

---

src/App.js
src/components/Layout/Sidebar.js
src/components/Widget/WorkshopApplicationCard.js
src/pages/DashboardPage.js
src/pages/WorkshopApplicationPage.js
src/redux/workshopRedux.js
src/sagas/authSagas.js
src/sagas/index.js
src/sagas/workshopSagas.js
src/utils/functions.js

With this pull request the workshop registration is added:
- Workshop application via `/workshop`
- Workshop status Card on `Dashboard`
fixes #37

37 workshop application

---

src/App.js
src/components/Layout/Sidebar.js
src/pages/WorkshopApplicationPage.js
src/pages/WorkshopOverviewPage.js
src/pages/administrator/WorkshopDetailsPage.js
src/pages/administrator/WorkshopListPage.js
src/utils/functions.js

- Workshop overview
- renamed /workshops to /workshop-list
- dirty fix for slower loading of the conferenceID compared to the page, causing badRequest to be sent

Workshop overview

---

src/components/ResetForm.js
src/pages/ProfilePage.js
src/redux/authRedux.js
src/sagas/authSagas.js
src/sagas/index.js

Change email or password while editing your profile
fixes #58

feat(): change email and password

---

.env
package.json
src/App.js
src/redux/authRedux.js
src/utils/functions.js
yarn.lock

500 Error handling

---

src/App.js
src/components/Layout/Sidebar.js
src/pages/WorkshopSuggestionPage.js
src/pages/administrator/PhasesPage.js
src/pages/administrator/WorkshopListPage.js
src/sagas/conferenceSagas.js

A user can submit a suggestion for his workshop if the phase has been activated. Administrators can change this in the phase page.
fix #69 
fix #70

Users can submit workshop suggestions

---

src/pages/administrator/PhasesPage.js

The downloaded CSV can now be used for serial letters. All Passwords are goruped by council.

fix(): return council passwords in a useful way

---

src/pages/ApplicationPage.js
src/pages/DashboardPage.js
src/sagas/conferenceSagas.js

fixes #75 
addFields will be dynamically parsed and  joined with the conference object. From now on, dynamic requirements of the event hosts can be implemented without having to change the database structure.

Participant agreement should be hyperlinked at registration

---

src/pages/administrator/ApplicationListPage.js
src/pages/administrator/PhasesPage.js
src/redux/conferenceRedux.js
src/sagas/conferenceSagas.js
src/sagas/index.js
src/utils/functions.js

Administrators can now export all applications, the list of workshops and all data necessary for badges inside the settings page
closes #77

Admins can now export data

---

src/components/AuthForm.js

better input validation
closes #11

Minimal Password Length

---

src/components/AuthForm.js

as fixed in #11 the account creation has now better UX.
Release the changes so that new account creations get better error messages

Input Validation on Account Creation

---

src/components/Widget/WorkshopApplicationCard.js
src/utils/functions.js

Fixes a bug where a user approved to the conference can see his workshops from past conferences

WorkshopApplications are now filtered by conference

---

src/components/Widget/UploadInformationCard.js
src/components/Widget/WorkshopApplicationCard.js
src/pages/ApplicationPage.js

- new upload information card  for buFaK Neuland
- optional Participant agreement
- ical export not hardcoded anymore

new uploadText and optional participantAgreement

---

package.json
src/App.js
src/components/Layout/Sidebar.js
src/components/PrivateRoute.js
src/components/voting/ButtonWithTimeout.js
src/components/voting/CouncilVote.js
src/components/voting/QuestionResults.js
src/components/voting/QuestionVotingActive.js
src/components/voting/VotingForm.js
src/pages/VotingListPage.js
src/pages/VotingPage.js
src/pages/superAdmin/ConferenceListPage.js
src/pages/superAdmin/QuestionDetailsPage.js
src/pages/superAdmin/QuestionListPage.js
src/redux/conferenceRedux.js
src/redux/index.js
src/redux/votingRedux.js
src/sagas/conferenceSagas.js
src/sagas/index.js
src/sagas/votingSagas.js
src/utils/functions.js
yarn.lock

First Version of Voting System

---

.github/workflows/nodejs.yml
src/components/AuthForm.js
src/utils/functions.js

bug(): authform redirects only after the conferenceId is set

---

src/components/Widget/UploadInformationCard.js
src/pages/ApplicationPage.js

154 additional information texts

---

src/components/Tab.js
src/components/Tabs.js
src/pages/ApplicationPage.js
src/pages/WorkshopSuggestionPage.js
src/pages/administrator/PhasesPage.js
src/styles/components/_tabs.scss
src/styles/reduction.scss

Info Texts and Workshop suggestion improvements

---

src/App.js
src/components/DetailsBody.js
src/components/Layout/Sidebar.js
src/config/globals.tsx
src/pages/TravellInfoPage.js
src/pages/administrator/PhasesPage.js
src/sagas/travelSagas.js
yarn.lock

158 travel infos

---

src/pages/administrator/PhasesPage.js

Change the separator for the conference application from comma to semicolon.

Edit: Change separator for application csv export

---

src/components/Widget/UploadInformationCard.js

Update UploadInformationCard.js no.2
